server:
  port: 80

eureka:
  client:
    register-with-eureka: false # false 也可以取值
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server01:7001/eureka
spring:
  application:
    name: provider-hystrix-order
feign:
  hystrix:
    enabled: true #如果处理自身的容错就开启。开启方式与生产端不一样。

#默认一秒
#ribbon:
#  ReadTimeout:  5000
#  ConnectTimeout: 5000