server:
  port: 9527
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
      - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
        #uri: http://localhost:8001   #匹配后提供服务的路由地址
        uri: lb://lvym-payment-service #动态路由
        predicates:
          - Path=/payment/get/**   #断言,路径相匹配的进行路由

      - id: payment_routh2
        #uri: http://localhost:8001
        uri: lb://lvym-payment-service #动态路由
        predicates:
          - Path=/payment/lb/**   #断言,路径相匹配的进行路由
          - After=2020-04-13T17:09:09.715+08:00[Asia/Shanghai]
         # - Cookie=username,lvym


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server01:7001/eureka
  instance:
    instance-id: lvym-gateway

