server:
  port: 7001
spring:
  application:
    name: lvym-eureka-server
eureka:
  instance:
    hostname: eureka-server01
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka-server01:7001/eureka/
      #defaultZone: http://eureka-server02:7002/eureka/,http://eureka-server03:7003/eureka/
  server:
    #关闭保护机制
    enable-self-preservation: false

    eviction-interval-timer-in-ms: 20000
