server:
  port: 8002

spring:
  application:
    name: lvym-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver        #mysql驱动包
    url: jdbc:mysql://192.168.146.182:3306/cloud2020?useUnicode=true&characterEncoding-utr-8&useSSL=false
    username: root
    password: Lvym777@
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lvym.springcloud.entities       #所有Entity别名类所在包
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server01:7001/eureka #,http://eureka-server02:7002/eureka,http://eureka-server03:7003/eureka
  instance:
    instance-id: lvym-payment02
    prefer-ip-address: true
    #客户端向服务端发送心跳时间
    lease-renewal-interval-in-seconds: 1
    #服务端在收到最后一次心跳的等待时间上限
    lease-expiration-duration-in-seconds: 2