server:
  port: 7002
spring:
  application:
    name: lvym-eureka-server02
eureka:
  instance:
    hostname: eureka-server02
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka-server01:7001/eureka/,http://eureka-server03:7003/eureka/
